### ISSUE TITLE
SecretStr and SecretBytes values are not respected

### ISSUE THREAD

**Issue by l1b3r** [ErhoSen/pydjantic#11]
Consider the following `settings.py`:

```python

import os
from pydantic import BaseSettings, SecretStr
from pydjantic import to_django

class Settings(BaseSettings):
    MY_SECRET: SecretStr

# Define a secret in the env so that Pydantic validation passes
os.environ["MY_SECRET"] = "i am a secret"

settings = Settings()
print(settings.dict())   # ✅ Will NOT print the actual secret value, which is good

to_django(settings)

print(MY_SECRET)         # ❌ Prints "**********", which is incorrect
```

Here is the output of running the above snippet:
```
{'MY_SECRET': SecretStr('**********')}
**********
```

The second `print` should have yielded `i am a secret` instead. Otherwise there is no way of using the secret value in the rendered settings.

**Comment by ErhoSen** [comment]
Variable `MY_SECRET` is not explicitly declared. It works because of a hack, and you should not build your code based on the hacks IMO.

You probably want something like this:
```py
from django.conf import settings

print(settings. MY_SECRET)
```

And it should work as expected

**Comment by ErhoSen** [comment]
Oh, got it 🤦🏻
