### ISSUE TITLE
feat: manage.py command to generate .env

### ISSUE THREAD

**Issue by estahn** [ErhoSen/pydjantic#6]
Would be great to be able to bootstrap a `.env` based of the defined structure. Ideally interactive and non-interactive.

**Comment by ErhoSen** [comment]
Hi
Didn't get it, you want some `./manage.py` command, that will create `settings.py` file like [this one](https://github.com/ErhoSen/pydjantic/blob/master/demo/demo/settings.py)?

**Comment by estahn** [comment]
The config classes read information from specific environment variables and/or a `.env` file. It would be great to be able to run `manage.py configure` (similar to `aws configure`) which asks for the required config vars and then saves them in `.env` file:

```
DJANGO_SECRET_KEY=abc
DB_USER=...
```

Just streamlining the dev experience more.

Btw great project 👍

**Comment by ErhoSen** [comment]
I'm not sure it's the right thing to do for such a little library as Pydjantic. 
1. Currently Pydjantic isn't a Django app. To run commands like `manage.py configure` we would need to transform the library into a Django app (with `management/commands`, `apps.py`, etc) and require users to install it (add `pydjantic.AppConfig` to INSTALLED_APPS settings).
2. From my point of view, it's pretty weird to install an app with basically single command in it. Also, the developer's flow will be weird as well: 
    * `django-admin startproject`, 
    * transform settings.py using `pydjantic` approach
    * add pydjantic to INSTALLED_APPS
    * run `manage.py configure`. 
3. The library itself isn't about `.env` files. It's just one of the options, how you can provide environment variables to your project. I'm not sure but it somehow breaks the single responsibility principle.

**Comment by estahn** [comment]
Fair enough. Thanks for thinking it through.
