### ISSUE TITLE
Support conn_max_age & ssl_require in BaseDBConfig

### ISSUE THREAD

**Issue by estahn** [ErhoSen/pydjantic#7]
We should be able to set conn_max_age & ssl_require in BaseDBConfig.

**Comment by ErhoSen** [comment]
Done #8  👍🏻

**Comment by estahn** [comment]
Thanks @ErhoSen

How would I specify this as part of an environment variable?

**Comment by ErhoSen** [comment]
Hm, didn't think about that.

**Comment by ErhoSen** [comment]
U wanna something like this 
`postgres://user:password@hostname:5432/database_name?conn_max_age=60&ssl_require=True`?

**Comment by estahn** [comment]
Yes, that looks exactly what I was thinking of.

There is also Django's ATOMIC_REQUESTS, not sure if that is supported by the parser lib though.

**Comment by ErhoSen** [comment]
@estahn I've updated Readme, take a look
<img width="901" alt="image" src="https://user-images.githubusercontent.com/5013076/180477247-a12c8549-c237-40de-a07c-cd05374fe9c9.png">


I believe it's your case. [See tests for usage](https://github.com/ErhoSen/pydjantic/blob/master/tests/test_db_config.py#L112-L135)
